### ISSUE TITLE
Compile errors

### ISSUE THREAD

**Issue by mcelrath** [commerceblock/mercury#12]
Things to note in your README:

You need to use an experimental branch of rust, not the stable branch:
```
rustup default nightly
```
The stable branch will generate a lot of errors along the lines of "Use of unstable feature `alloc`" and `maybe_uninit`.

FYI I didn't have any problem with the `rust-pallier` library indicated in the README.

**Comment by mcelrath** [comment]
Second comment about the client:

The paths are messed up for the client. `iclient.sh` should point to `target/debug/cli` instead of `client/target/release/cli` (and I should really figure out rust debug vs release builds...)

Also the `Settings.toml` file is in `client/` which will cause `iclient.sh` to barf since it's not in the same directory. `iclient.sh = cd client && cargo run`

PR incoming for this...

**Comment by tomossomot** [comment]
Thanks for noticing and sorting these. 

The paillier library issue was fixed, I'll remove the warning in my next merge.
