### ISSUE TITLE
GetStateChain returns incorrect value data after statecoin has been transferred

### ISSUE THREAD

**Issue by 86667** [commerceblock/mercury#130]
After transfer a statecoin worth 5BTC receives back value 5.000007BTC from `/info/statechain/`

**Comment by tomt1664** [comment]
The statechain amount in the server is calculated from the backup tx (all outputs + fee). The fee is hardcoded at the moment and must be the same as that set in the wallet (which builds the backup tx). Temporary fix is to make sure they are both the same.
