### ISSUE TITLE
Mainstay Integration

### ISSUE THREAD

**Issue by tomossomot** [commerceblock/mercury#23]
Commit to SMT root via Mainstay.

**Comment by tomt1664** [comment]
Tasks: 
1.  Set up process to push SMT root to a specified Mainstay slot at regular (1s?) intervals (or at every update). 
2. Instantiate new database to hold mainstay slot proofs for the SMT root. 
3. Retrieve slot proofs at regular intervals. 
4. Attach slot proofs to SMT paths to send to wallets on request. 
5. Wallet retrieves slot-proofs along with SMT paths for PoP.

**Comment by tomossomot** [comment]
1. [Complete](https://github.com/commerceblock/mercury/pull/35)

**Comment by tomossomot** [comment]
2. Complete in [postgres integration](https://github.com/commerceblock/mercury/pull/38)

**Comment by tomossomot** [comment]
4. Complete via `get_smt_proof` and `get_smt_root` API calls

**Comment by tomossomot** [comment]
5. Complete. Wallet gets proofs and roots via `get_smt_proof` and `get_smt_root` API calls
