### ISSUE TITLE
Problem building with openssl 1.1.1g

### ISSUE THREAD

**Issue by lawlawlaw** [commerceblock/mercury#30]
Lawrences-MacBook-Pro:mercury lawrence$ cargo build
   Compiling block-buffer v0.3.3
   Compiling standback v0.2.3
   Compiling rustversion v1.0.2
   Compiling error-chain v0.12.2
   Compiling openssl-sys v0.6.7
   Compiling quote v1.0.3
   Compiling jobserver v0.1.21
   Compiling time v0.1.43
error: failed to run custom build command for `openssl-sys v0.6.7`

Caused by:
  process didn't exit successfully: `/Users/lawrence/Projects/mercury/target/debug/build/openssl-sys-63c28b95e061f8d7/build-script-build` (exit code: 101)
--- stdout
cargo:rustc-link-search=native=/usr/local/Cellar/openssl@1.1/1.1.1g/lib
cargo:rustc-link-lib=ssl
cargo:rustc-link-lib=crypto
TARGET = Some("x86_64-apple-darwin")
OPT_LEVEL = Some("0")
TARGET = Some("x86_64-apple-darwin")
HOST = Some("x86_64-apple-darwin")
TARGET = Some("x86_64-apple-darwin")
TARGET = Some("x86_64-apple-darwin")
HOST = Some("x86_64-apple-darwin")
CC_x86_64-apple-darwin = None
CC_x86_64_apple_darwin = None
HOST_CC = None
CC = None
HOST = Some("x86_64-apple-darwin")
TARGET = Some("x86_64-apple-darwin")
HOST = Some("x86_64-apple-darwin")
CFLAGS_x86_64-apple-darwin = None
CFLAGS_x86_64_apple_darwin = None
HOST_CFLAGS = None
CFLAGS = None
DEBUG = Some("true")
running: "cc" "-O0" "-ffunction-sections" "-fdata-sections" "-fPIC" "-g" "-m64" "-I" "/usr/local/Cellar/openssl@1.1/1.1.1g/include" "-Wall" "-Wextra" "-o" "/Users/lawrence/Projects/mercury/target/debug/build/openssl-sys-4eacbcb00f23a914/out/src/openssl_shim.o" "-c" "src/openssl_shim.c"
cargo:warning=src/openssl_shim.c:115:41: warning: unused parameter 'ctx' [-Wunused-parameter]
cargo:warning=int SSL_CTX_set_ecdh_auto_shim(SSL_CTX *ctx, int onoff) {
cargo:warning=                                        ^
cargo:warning=src/openssl_shim.c:126:7: error: incomplete definition of type 'struct dh_st'
cargo:warning=    dh->p = p;
cargo:warning=    ~~^
cargo:warning=/usr/local/Cellar/openssl@1.1/1.1.1g/include/openssl/ossl_typ.h:104:16: note: forward declaration of 'struct dh_st'
cargo:warning=typedef struct dh_st DH;
cargo:warning=               ^
cargo:warning=src/openssl_shim.c:127:7: error: incomplete definition of type 'struct dh_st'
cargo:warning=    dh->g = g;
cargo:warning=    ~~^
cargo:warning=/usr/local/Cellar/openssl@1.1/1.1.1g/include/openssl/ossl_typ.h:104:16: note: forward declaration of 'struct dh_st'
cargo:warning=typedef struct dh_st DH;
cargo:warning=               ^
cargo:warning=src/openssl_shim.c:128:7: error: incomplete definition of type 'struct dh_st'
cargo:warning=    dh->q = q;
cargo:warning=    ~~^
cargo:warning=/usr/local/Cellar/openssl@1.1/1.1.1g/include/openssl/ossl_typ.h:104:16: note: forward declaration of 'struct dh_st'
cargo:warning=typedef struct dh_st DH;
cargo:warning=               ^
cargo:warning=src/openssl_shim.c:137:13: error: incomplete definition of type 'struct x509_st'
cargo:warning=    return x->cert_info ? x->cert_info->extensions : NULL;
cargo:warning=           ~^
cargo:warning=/usr/local/Cellar/openssl@1.1/1.1.1g/include/openssl/ossl_typ.h:121:16: note: forward declaration of 'struct x509_st'
cargo:warning=typedef struct x509_st X509;
cargo:warning=               ^
cargo:warning=src/openssl_shim.c:137:28: error: incomplete definition of type 'struct x509_st'
cargo:warning=    return x->cert_info ? x->cert_info->extensions : NULL;
cargo:warning=                          ~^
cargo:warning=/usr/local/Cellar/openssl@1.1/1.1.1g/include/openssl/ossl_typ.h:121:16: note: forward declaration of 'struct x509_st'
cargo:warning=typedef struct x509_st X509;
cargo:warning=               ^
cargo:warning=1 warning and 5 errors generated.
exit code: 1

--- stderr
thread 'main' panicked at '

Internal error occurred: Command "cc" "-O0" "-ffunction-sections" "-fdata-sections" "-fPIC" "-g" "-m64" "-I" "/usr/local/Cellar/openssl@1.1/1.1.1g/include" "-Wall" "-Wextra" "-o" "/Users/lawrence/Projects/mercury/target/debug/build/openssl-sys-4eacbcb00f23a914/out/src/openssl_shim.o" "-c" "src/openssl_shim.c" with args "cc" did not execute successfully (status code exit code: 1).

', /Users/lawrence/.cargo/registry/src/github.com-1ecc6299db9ec823/gcc-0.3.55/src/lib.rs:1672:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.

warning: build failed, waiting for other jobs to finish...
error: build failed

**Comment by tomossomot** [comment]
Openssl@1.1 with rustc 1.45.0-nightly works fine for me. Which rust version are you on?

**Comment by tomossomot** [comment]
Ah, I'm running Openssl 1.1.1d.
