### ISSUE TITLE
Select address from CLI 

### ISSUE THREAD

**Issue by nicosey** [commerceblock/mercury#96]
When there are multiple addresses in the CLI tool it's not clear which address the statecoin will be sent from.
Need to have send function choose an address.

**Comment by tomt1664** [comment]
The statechain ID must be specified when sending a single statecoin, using the `-i` option in `transfer_sender`

`State Entity balance: 

StateChain ID:					Confirmed:	Unconfirmed:	Locktime:
91bfbec1-2ab6-4083-b154-4c386f8d151b		4000		0		13345
aed71ee9-0ee9-477d-8894-4227579c782a		5000		0		13345

$ cli wallet transfer-sender -a sc1qgkhag7jse2pa4vnuq2cuv2awwggv34te7jx4ftvzg3f52gsenjgcla4fdu -i aed71ee9-0ee9-477d-8894-4227579c782a`
